Update pdb2sqlcore.py
DeepRank/pdb2sql pull request #72
Opened 2022-02-22 13:01 UTC by DTRademaker

Add sorting of the values to the 'get' function. This to fix a bug that sometimes occurs when comparing the atoms between multiple pdbs ( e.g. when using StructureSimilarity script). The bug is caused by pdbs having not the same atom-name (e.g. CA C CB O N...) order.

2022-02-22 16:18 UTC, CunliangGeng requested changes
Hi Daniel, thanks for fixing the atom order issue.
Considering that the atom order only affects `StructureSimilarity`, I suggest adding a parameter `order` to the `get` method: `get(self, columns, tablename='ATOM',  order=None, **kwargs)`. The `order` is None by default; if you want to order the atoms, then set it to e.g. `order='chainID,resSeq,name'`. Could you please refactor the code in this way?

After refactoring the code, please also check the following tasks
- [ ] update the `get` method used in `StructureSimilarity`
- [ ] add unittest in `test_pdb2sqlcore.py` to test the new parameter
- [ ] make sure all tests are passed : -)

2022-08-19 12:57 UTC, LilySnow commented
Hi Cunliang, I do not think we need an order parameter, right? I will accept this change.

2022-08-19 14:39 UTC, DTRademaker commented
do not accept yet please

2022-08-19 16:10 UTC, NicoRenaud commented
Hi all, I’m not sure I would change the way get returns the values. The behavior described here was precisely what was intended. Since the issue is only in structure similarity I would add the sorting option there and not in get.

2022-08-22 07:26 UTC, CunliangGeng commented
Agree with Nico. That's also why I suggested adding an option to `get` itself.

2022-08-22 11:09 UTC, NicoRenaud commented
Adding the `order` argument to get is a solution but it makes get more complicated ... I would really simply fix that in StructureSimilarity and not touch `get`. The `get` method is central to all the data pipelines we have created (iscore, deeprank, deeprank GNN) so modifying it is not a trivial decision. Adding an order option would also make get do two things (SQL query + sorting) and that's 1 thing too many :)

2022-08-23 12:16 UTC, LilySnow commented
Hi Nico, there seems no other way to fix this bug without changing the get function. We cannot fix StructureSimilarity downstream...

2022-08-23 13:15 UTC, NicoRenaud commented
Hi Li, I'm not sure what the issue is, but the ordering can surely be done  outside of the get function by simply getting the chainID, resSeq, name, x,y,z and ordering the resulting array ....

2022-08-23 14:38 UTC, DTRademaker commented
> Hi Li, I'm not sure what the issue is, but the ordering can surely be done outside of the get function by simply getting the chainID, resSeq, name, x,y,z and ordering the resulting array according to the chain,res,name values. Or am i missing something ?
> 
> In any case changing the default behavior of get may break the data processing pipeline of all the codes that rely on it (iscore, deeprank, ... ). So I would be careful about it :)

The 'get' function is called 12 times in the 'StructureSimilarity' script for retrieving xyz coordinates. These should all be adjusted then. Yes of course we can do it by retrieving 'chainID, resSeq, name, x,y,z', sorting it and extract the xyz and that times 12. But that would miss the point of having the get function in the first place where you specify what you need. Especially since this could also be done, as implemented by my suggestion, directly in the sql command of the 'get' function. Which I might add is computationally also faster.  I understand the concern that it 'might' impact other software. But I could also argue that it 'might' actually improve the other software since the atom-order is currently completely dependent on the pdb-atom-order which can sometimes differ from pdb to pdb. And to be honest I can not imagine any scenario where having the residue atoms in a consistent order would disturb the other code... but that could of course also be my lack of imagination. The code I am suggesting passed all unit-tests, and should therefore also work fine for the other software right?

2022-10-03 12:28 UTC, NicoRenaud commented
Hey @DTRademaker  @LilySnow  @CunliangGeng, should we merge that ?

2022-10-03 21:01 UTC, DTRademaker commented
> Hey @DTRademaker @LilySnow @CunliangGeng, should we merge that ?

Fine with me :)

2022-10-04 16:07 UTC, NicoRenaud commented
@LilySnow  if you also agree can you merge the PR ?

2022-10-28 04:11 UTC, closed without merging